### ISSUE TITLE
ModuleNotFoundError: No module named 'vector3'

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [rayzchen/pyunity#12]
I am a new user to pyunity..
i installed it with
```pip install pyunity```

I was trying out the examples..
```python -m pyunity 1```
it resulted in error:
Error log:
```
PS C:\Users\Lenovo> python -m pyunity 1
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Traceback (most recent call last):
  File "C:\Program Files\Python38-32\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python38-32\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python38-32\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Program Files\Python38-32\lib\site_packages\pyunity\__init__.py",  line 131, in <module>
    from .audio import *
  File "audio.py", line 13, in init pyunity.audio
  File "core.py", line 1, in init pyunity.core
ModuleNotFoundError: No module named 'vector3'
```
I have tried whatever i can do.. but i can't fix it nor find any module with name "vector3" on the internet..

Specs (if you need):
```
Python Version: Python 3.8.9
OS: Windows 7 SP 1
Processor: Intel core i3 (x86)
```

**Comment by rayzchen** [comment]
Ah i know why. Please download [this file](https://github.com/rayzchen/pyunity/raw/releases/0.4.0/pyunity-0.4.0-cp38-cp38-manylinux1_x86_64.whl) and put that in your working directory. Then run `pip install pyunity-0.4.0.tar.gz` which installs the latest build of pyunity. This issue has been marked in issue #7 and has been fixed, but I havent created a new release which has it. In the meantime, clone the repo and install from there (more details at pyunity.readthedocs.io)

**Comment by Whirlpool-Programmer** [comment]
i think that the file you gave me is for amd processors with x64 architecture..
and i have intel 32 bit laptop..
is there a file something like: pyunity-0.4.0-cp38-cp38-win32.whl

**Comment by Whirlpool-Programmer** [comment]
FINALLY!
FIX:
i cloned the whole repository and went to the directory of the project and opened pwsh and entered ```python setup.py install```
that's it!
it successfully installed PyUnity 0.4.0!

and everything worked fine!

**Comment by Whirlpool-Programmer** [comment]
I used the source code of this repository instead and compiled it with ```python setup.py install```
it gave this output
```
PS C:\Users\Lenovo\Downloads\pyunity-master\pyunity-master> python setup.py install
running install
running bdist_egg
running egg_info
writing pyunity.egg-info\PKG-INFO
writing dependency_links to pyunity.egg-info\dependency_links.txt
writing requirements to pyunity.egg-info\requires.txt
writing top-level names to pyunity.egg-info\top_level.txt
error: package directory 'src' does not exist
```
I don't think everything was done fine..
so.. any .whl file for me? 
or .tar.gz?

**Comment by rayzchen** [comment]
Huh? I don’t know why that happened...

**Comment by rayzchen** [comment]
Try https://github.com/rayzchen/pyunity/raw/master/dist/0.4.0/pyunity-0.4.0-cp38-cp38-win32.whl

**Comment by rayzchen** [comment]
Send the result of dir

**Comment by rayzchen** [comment]
ahh ik y now, run `python prepare.py` first before you build.

**Comment by rayzchen** [comment]
pull the new changes and try again

**Comment by Whirlpool-Programmer** [comment]
looks like everything is fine but i have another problem..
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with microsoft c++ build tools
```
I thought you can't do any help now!  i just have to install that..
but i am getting irritated by just one thing..
C++ BUILD TOOLS WILL TAKE 3gb+ storage!!
i only have data pack of 2gb!

**Comment by Whirlpool-Programmer** [comment]
can you please build a wheel file for the package?
with name something like:
```pip install pyunity-0.4.0-cp38-cp38-win32.whl```

**Comment by rayzchen** [comment]
Ok, here is the link: master/dist/0.4.0/pyunity-0.4.0-cp38-cp38-win32.whl

**Comment by rayzchen** [comment]
> looks like everything is fine but i have another problem..
> 
> ```
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with microsoft c++ build tools
> ```
> 
> I thought you can't do any help now! i just have to install that..
> but i am getting irritated by just one thing..
> C++ BUILD TOOLS WILL TAKE 3gb+ storage!!
> i only have data pack of 2gb!

PyUnity uses Cython compiling to optimize, as a result you must have Microsoft C++ Build Tools. Fortunately, I try to build the package myself for anyone who doesn't have buildtools. In the future, to find relevant packages, look in the `dist` folder in the master branch or check in the `releases` branch. In total there are 16 different compiled wheels.

**Comment by Whirlpool-Programmer** [comment]
I successfully installed pyunity from the ```dist``` folder..
but!
there's a problem!

any time i use the ```import pyunity``` or ```from pyunity import *```
error comes!
the error:
```
PS E:\Penguin> python -u "e:\penguin\my_pyunity_project.py"
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Traceback (most recent call last):
  File "e:\penguin\my_pyunity_project.py", line 9, in <module>
    from pyunity.examples.example1 import main
  File "C:\Program Files\Python38-32\lib\site-packages\pyunity\__init__.py", line 165, in <module>
    from . import loader as Loader  # lgtm[py/import-own-module]
  File "loader.py", line 10, in init pyunity.loader
  File "C:\Program Files\Python38-32\lib\site-packages\pyunity\scenes\__init__.py", line 10, in <module>
    from . import sceneManager as SceneManager
  File "sceneManager.py", line 13, in init pyunity.scenes.sceneManager
ImportError: cannot import name scenes
```
Looks like i am finding bugs!

**Comment by rayzchen** [comment]
hmm ill look through it

**Comment by rayzchen** [comment]
Found the bug, its now fixed but there is no wheel yet, ill build one asap but i cant rn

**Comment by Whirlpool-Programmer** [comment]
> Found the bug, its now fixed but there is no wheel yet, ill build one asap but i cant rn

you build the wheel and update the pyunity repository then comment here and i will try it.

**Comment by rayzchen** [comment]
https://github.com/rayzchen/pyunity/raw/master/dist/0.4.0/pyunity-0.4.0-cp38-cp38-win32.whl here ya go

**Comment by Whirlpool-Programmer** [comment]
hey! sorry for this much late response.. I was actually out of london..
anyways..
Now the bugs are fixed!

I am closing this issue..
