### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by rayzchen** [rayzchen/pyunity#5]
Importing is broken, meshes are broken, setup.py is broken, compiling is broken, everything is broken. I need some time to fix it all.

**Comment by rayzchen** [comment]
Fixed the meshes

**Comment by rayzchen** [comment]
More information:

```python
from . import examples
examples.show()
```

The above code works fine, and it is the exact same as the contents of `__main__.py`. However, when I run `py -m pyunity` then the entire thing breaks with error:

```Traceback (most recent call last):
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\daoxi\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyunity\__init__.py", line 131, in <module>
    from .audio import *
  File "audio.py", line 13, in init pyunity.audio
  File "core.py", line 1, in init pyunity.core
ModuleNotFoundError: No module named 'vector3'```

**Comment by Ixyk-Wolf** [comment]
I installed vector and it worked for me but now I get the error 
![image](https://user-images.githubusercontent.com/68626630/116001983-42e20a00-a5ac-11eb-9d06-8f12eb505c5b.png)

**Comment by rayzchen** [comment]
Hello, can you elaborate on what you mean by "installing vector3"? Also it would help if you sent me your discord username.

**Comment by Ixyk-Wolf** [comment]
After like 2 minutes the vector3 import error came back. I fixed it by renaming the .pyd file to just vector.pyd instead of vector3.cp38-win32.pyd and it works but I still get the cannot import name config even thought I renamed it to just config.pyd.
Python 3.8.9
Windows 10

**Comment by rayzchen** [comment]
I dont think thats how its meant to work? also what is ur discord btw

**Comment by rayzchen** [comment]
Just a comment, compiling is fixed

**Comment by Ixyk-Wolf** [comment]
Well, I don't truly know. I really hope this is usable soon because I think it's awesome and I hope my laptop can support it,

**Comment by rayzchen** [comment]
In the docs on pyunity.readthedocs.io there is a temporary fix, though it doesn't include the optimizations that Cython provides.

**Comment by rayzchen** [comment]
Same info has been updated in README.md

**Comment by rayzchen** [comment]
Imma reopen an issue for the compiling because this issue is way too vague from its title
